README.md
bump-version/README.md
bump-version/action.yml
bump-version/get-conventional-bump.ts
bump-version/index.integration.spec.ts
bump-version/index.ts
jest.config.js
package-lock.json
package.json
test/setup.ts
test/utils/action-with.ts
test/utils/env.ts
test/utils/index.ts
test/utils/retry-until.ts
test/utils/wait.ts
tsconfig.json
utils/index.ts
utils/updateJSON.ts

Adds the action to bump a version according to our release rules and process. Also sorts out any tooling in the actions repo.
- See comprehensive test suite.
6 hours
Related #2
Related #8 
@saihaj @bhajneet

feat(bump-version): add bump version action

---

commitlint.config.js

build: disable max body length for commit messages

---

.eslintrc

lint: enforce naming conventions

---

.vscode/extensions.json
.vscode/settings.json

Based on #10 
@bhajneet @saihaj

build: add recommended extensions and settings

---

bump-version/README.md
bump-version/action.yml
bump-version/index.ts

Adds outputs of version.
5 mins
@bhajneet @saihaj

feat(bump-version): add previous and next version outputs

---

README.md
package-lock.json
package.json
publish-github/README.md
publish-github/action.yml
publish-github/create-release.ts
publish-github/index.integration.spec.ts
publish-github/index.ts
publish-github/upload-assets.ts
utils/get-inputs.ts
utils/index.ts

Adds publish GitHub action.
To be tested. A little tricky to test if planning on just mocking out everything, so might use real repository.
2 hours

feat(publish-github): add publish github action

---

README.md
publish-branch/README.md
publish-branch/action.yml
publish-branch/get-branches.ts
publish-branch/index.integration.spec.ts
publish-branch/index.ts
test/utils/action-with.ts

Adds publish release branches action.
- Suite
3-4 hours

feat(publish-branch): add action to publish release branches

---

.eslintignore
.github/workflows/continuous-integration.yml
.github/workflows/latest-release.yml
.github/workflows/next-release.yml
README.md
bump-version/action.yml
bump-version/index.ts
generate-changelog/README.md
generate-changelog/action.yml
generate-changelog/index.ts
package-lock.json
package.json
publish-branch/action.yml
publish-docker/README.md
publish-docker/action.yml
publish-github/README.md
publish-github/action.yml
publish-github/create-release.ts
publish-github/index.ts
publish-github/notify.ts
publish-npm/README.md
publish-npm/action.yml
tsconfig.json
types/conventional-changelog-angular.d.ts

Adds remaining GitHub actions:
- publish to npm/gh package
- publish to dockerhub/gh package
- generate changelog (no tests and behaviour is not perfect yet)
Fix #

feat: add remaining GitHub Actions

---

.github/workflows/continuous-integration.yml
.github/workflows/latest-release.yml
.github/workflows/next-release.yml

ci: add missing parenthesis to if condition in release workflows

---

.github/workflows/continuous-integration.yml
.github/workflows/latest-release.yml
.github/workflows/next-release.yml

ci: remove generate changelog from next-release workflow

---

.github/workflows/next-release.yml

ci: re-add generate-changelog step to next-release workflow

---

bump-version/action.yml
generate-changelog/action.yml
publish-branch/action.yml
publish-github/action.yml

fix: revert action runner back to node12

---

.github/workflows/continuous-integration.yml
package-lock.json
package.json

build: update @vercel/ncc

---

.github/workflows/continuous-integration.yml

ci: exclude release branches triggering CI workflow

---

.github/workflows/release-latest.yml
.github/workflows/release-next.yml
.github/workflows/trigger-release.yml
bump-version/index.ts
generate-changelog/index.ts
publish-branch/index.ts
publish-github/index.ts

Fix #
require.main === module does not work currently with ncc

ci: trigger release jobs when PR is merged

---

.github/workflows/trigger-release.yml

ci: add missing expression braces to trigger-release workflow

---

.github/workflows/release-latest.yml
.github/workflows/release-next.yml
.github/workflows/trigger-release.yml

ci: use job names according to GItHub action naming allowances

---

bump-version/index.ts
package-lock.json
package.json

fix(bump-version): add missing context import

---

.github/workflows/trigger-release.yml

ci: use user's github token with elevated permission in trigger release

---

.github/workflows/trigger-release.yml

ci: remove elevated github_token from trigger release workflow

---

README.md
commit-pr-has-label/README.md
commit-pr-has-label/action.yml
commit-pr-has-label/index.ts

feat(commit-pr-has-label): add action to check if associated PR has label

---

.github/workflows/log-owner.yml

ci: add log owner

---

.github/workflows/trigger-release.yml

ci: log context repo name and owner

---

.github/workflows/trigger-release.yml

ci: use GH_BOT_TOKEN secret in trigger release workflow

---

bump-version/index.ts

fix(bump-version): load package.json from path input

---

publish-github/index.ts

fix(publish-github): only acquire version via annotated tags, not lightweight

---

publish-github/index.ts
publish-github/notify.ts

The notify on PR feature is incorrectly called and breaks tests. This PR disables it.

fix(publish-github): disable notify on merged PR

---

.github/workflows/release-latest.yml
.github/workflows/release-next.yml

ci: specify version of reusable release workflow

---

.github/workflows/release-latest.yml
.github/workflows/release-next.yml

ci: fix reusable release workflow path

---

integrate-commits/action.yml

The action provided invalid syntax :(

fix(integrate-commits): add shell property and remove unsupported if

---

bump-version/index.ts
generate-changelog/index.ts
publish-github/README.md
publish-github/action.yml
publish-github/create-release.ts
publish-github/index.integration.spec.ts

Sometimes there's a `v` and sometimes there isn't... This should mean there always is ;)

fix: tidy up release names and commit messages

---

bump-version/index.ts

fix(bump-version): sort by semver if git tag creatordate is same
